/*
You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

b[0] is equal to a[0];
b[1] is equal to the last element of a;
b[2] is equal to a[1];
b[3] is equal to the second-last element of a;
b[4] is equal to a[2];
b[5] is equal to the third-last element of a;
and so on.
*/

boolean solution(int[] a) {
    int left = 0;
    int right = a.length - 1;
    int prevRight = Integer.MIN_VALUE;
    
    while (left < right){
        if (a[left] < a[right] && a[left] > prevRight){
            prevRight = a[right];
            left++;
            right--;
        }
        else{
            
            return false;
        }
    }
    
    //return true;
    return (a[left] > prevRight) || left > right;
    
}
